apiVersion: v1
kind: Service
metadata:
  name: rancher-ai-chat
  namespace: cattle-ai-agent-system
  labels:
    app: rancher-ai-chat
spec:
  type: {{ .Values.chat.service.type }}
  selector:
    app: rancher-ai-chat
  ports:
    - port: 80
      targetPort: {{ .Values.chat.service.port }}
      protocol: TCP
      name: http