apiVersion: v1
kind: PersistentVolume
metadata:
  name: rancher-ai-mysql-pv
  namespace: cattle-ai-agent-system
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data/mysql-local
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual