apiVersion: v1
kind: Service
metadata:
  name: rancher-ai-redis
  labels:
    app: rancher-ai-redis
spec:
  type: {{ .Values.redis.service.type }}
  ports:
    - port: {{ .Values.redis.service.port }}
      targetPort: {{ .Values.redis.service.targetPort }}
  selector:
    app: rancher-ai-redis