aiAgent:
  image:
    repository: ghcr.io/rancher-sandbox/rancher-ai-agent
    tag: v0.0.1-alpha.30
    pullPolicy: IfNotPresent
mcp:
  image:
    repository: ghcr.io/rancher-sandbox/rancher-ai-mcp
    tag: v0.0.1-alpha.23
    pullPolicy: IfNotPresent

redis:
  image:
    repository: redis
    tag: latest
    pullPolicy: IfNotPresent

  replicaCount: 1

  service:
    type: ClusterIP
    port: 6379

  useConfig: true
  redisConfig: |-
    bind 0.0.0.0
    protected-mode no
    port 6379
    tcp-backlog 511
    timeout 0
    tcp-keepalive 300
    daemonize no
    supervised no
    loglevel notice
    logfile ""
    databases 16
    save 900 1
    save 300 10
    save 60 10000
    rdbcompression yes
    rdbchecksum yes
    lua-time-limit 5000
    slowlog-log-slower-than 10000
    slowlog-max-len 128
    notify-keyspace-events ""

  persistence:
    enabled: false
    storageClass: ""
    accessMode: ReadWriteOnce
    size: 1Gi

  resources: {}

db:
  replicaCount: 1
  service:
    type: ClusterIP
    port: 3306
  mysql:
    image:
      repository: mysql
      tag: "8"
      pullPolicy: IfNotPresent
    rootPassword: "rancher-ai"
    database: "rancher-ai"
    persistence:
      size: 1Gi
      storageClass: manual
  supervisor:
    image:
      repository: ghcr.io/torchiaf/rancher-ai-db
      tag: v1.0.2
      pullPolicy: IfNotPresent
    redis:
      channel: "channel:history:s-*:r-*"

llmModel: ""
ollamaUrl: ""
googleApiKey:
openaiApiKey:
activeLlm: # ollama, gemini, openai
# Enable RAG with embedded rancher documentation
rag:
    enabled: false
    embeddings_model:
langfuseSecretKey:
langfusePublicKey:
langfuseHost:
insecureSkipTls: false
log:
  level: info
