aiAgent:
  image:
    repository: ghcr.io/torchiaf/rancher-ai-agent
    tag: v1.0.56
    pullPolicy: Always
mcp:
  image:
    repository: ghcr.io/rancher-sandbox/rancher-ai-mcp
    tag: v0.1.1
    pullPolicy: IfNotPresent

db:
  replicaCount: 1
  service:
    type: ClusterIP
    port: 5432
  postgres:
    image:
      repository: postgres
      tag: "18"
      pullPolicy: IfNotPresent
    password: "password"
    user: "postgres"
    name: "postgres"
    persistence:
      size: 1Gi
      storageClass: manual
  supervisor:
    enabled: true
    image:
      repository: ghcr.io/torchiaf/rancher-ai-db-2
      tag: v1.0.2
      pullPolicy: IfNotPresent
    agent:
      summaryUrl: "ws://rancher-ai-agent:80/agent/ws/summary"

chat:
  replicaCount: 1
  image:
    repository: ghcr.io/torchiaf/rancher-ai-chat-api
    tag: v1.0.36
    pullPolicy: IfNotPresent

  service:
    type: ClusterIP
    port: 5000

  readinessProbe:
    path: /health
    port: 5000
    initialDelaySeconds: 5
    periodSeconds: 10
  livenessProbe:
    path: /health
    port: 5000
    initialDelaySeconds: 10
    periodSeconds: 20

llmModel: ""
ollamaLlmModel: ""
geminiLlmModel: ""
openaiLlmModel: ""
bedrockLlmModel: ""
ollamaUrl: ""
googleApiKey:
openaiApiKey:
openaiUrl:
awsBedrock:
  bearerToken:
  accessKeyId:
  secretAccessKey:
  region:
activeLlm: # ollama, gemini, openai, bedrock
# Enable RAG with embedded rancher documentation
rag:
    enabled: false
    embeddings_model:
    pvc:
langfuseSecretKey:
langfusePublicKey:
langfuseHost:
dbManager:
  enabled: true
insecureSkipTls: false
llmMock:
  enabled: false
  url: ""
log:
  level: info
